@service-port = 3001
### 403 forbiden mutation false
POST http://localhost:{{service-port}}/mutation
Content-Type: application/json

{
    "dna": [
        "ATGCGA",
        "CTGTGC",
        "TTATGT",
        "AGAACG",
        "CCCTTA",
        "TCACTG"
        ]
}
### 200 Ok mutation true

POST http://localhost:{{service-port}}/mutation
Content-Type: application/json

{
    "dna": [
        "ATGCGA",
        "CAGTGC",
        "TTATGT",
        "AGAAGG",
        "CCCCTA",
        "TCACTG"
    ]
}

### invalid data

POST http://localhost:{{service-port}}/mutation
Content-Type: application/json
{
    "dna": [
        "ATGCGA",
        "CAGTGC",
        "TTATGT",
        "AGAAGG",
        "CCCCTA",
        "TCXCTG"
    ]
}

### get stats

GET http://localhost:{{service-port}}/stats
